name: Release notes

on:
#  push:
#    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter@v5.21.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
